EisenhowerMatrix.Web/Models/TodoTaskOldSchool/CreateTaskModel.cs
using System.ComponentModel.DataAnnotations;

namespace EisenhowerMatrix.Web.Models.TodoTaskOldSchool
{
    public class CreateTaskModel
    {
        [Required]
        [MaxLength(1024)]
        public string Name { get; set; }

        [Range(0, 10, ConvertValueInInvariantCulture = true, ErrorMessage = "Value should be in {1}-{2} range")]
        public double Urgency { get; set; }

        [Range(0, 10, ConvertValueInInvariantCulture = true, ErrorMessage = "Value should be in {1}-{2} range")]
        public double Importance { get; set; }
    }
}

EisenhowerMatrix.Web/Models/TodoTaskOldSchool/IndexModel.cs
using System.Collections.Generic;

namespace EisenhowerMatrix.Web.Models.TodoTaskOldSchool
{
    public class IndexModel
    {
        public IList<TaskModel> Tasks { get; set; } = new List<TaskModel>();
    }
}

EisenhowerMatrix.Web/Models/TodoTaskOldSchool/TaskModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EisenhowerMatrix.Web.Models.TodoTaskOldSchool
{
    public class TaskModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public double Urgency { get; set; }

        public double Importance { get; set; }

        public bool IsFinished { get; set; }
    }
}

EisenhowerMatrix.Web/Controllers/ErrorsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using EisenhowerMatrix.Web.Models.Errors;
using Microsoft.AspNetCore.Mvc;

namespace EisenhowerMatrix.Web.Controllers
{
    public class ErrorsController : Controller
    {
        public IActionResult Error()
        {
            var errorModel = new ErrorModel();
            errorModel.RequestId = Activity.Current?.Id ?? "";

            return View(errorModel);
        }
    }
}

EisenhowerMatrix.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace EisenhowerMatrix.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index() => View();
        public IActionResult About() => View();
        public IActionResult Privacy() => View();
    }
}

EisenhowerMatrix.Web/Controllers/TodoTaskOldSchoolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using EisenhowerMatrix.BusinessLogic;
using EisenhowerMatrix.BusinessLogic.Models;
using EisenhowerMatrix.Entities;
using EisenhowerMatrix.Web.Models.TodoTaskOldSchool;
using Microsoft.AspNetCore.Mvc;

namespace EisenhowerMatrix.Web.Controllers
{
    public class TodoTaskOldSchoolController : Controller
    {
        private ITodoTaskService todoTaskService;

        public TodoTaskOldSchoolController(ITodoTaskService todoTaskService)
        {
            this.todoTaskService = todoTaskService;
        }

        public async Task<IActionResult> Index(CancellationToken token)
        {
            var tasks = await this.todoTaskService.GetAsync(new ToDoTaskFilter
            {
                ShowOnlyNonFinished = false
            }, token);

            var indexModel = new IndexModel();
            indexModel.Tasks = tasks.Select(x => new TaskModel
            {
                Id = x.Id,
                Name = x.Name,
                Urgency = x.Urgency,
                Importance = x.Importance,
                IsFinished = x.IsFinished
            }).ToList();

            return View(indexModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new CreateTaskModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateTaskModel model, CancellationToken token)
        {
            if (ModelState.IsValid)
            {
                await this.todoTaskService.CreateAsync(new TodoTask
                {
                    Name = model.Name,
                    Urgency = model.Urgency,
                    Importance = model.Importance,
                    IsFinished = false
                }, token);

                return RedirectToAction(nameof(Index));
            }
            
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id, CancellationToken token)
        {
            var task = await this.todoTaskService.GetAsync(id, token);

            if (task != null)
            {
                await this.todoTaskService.DeleteAsync(task, token);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> MarkAsFinished(int id, CancellationToken token)
        {
            var task = await this.todoTaskService.GetAsync(id, token);

            if (task != null)
            {
                task.IsFinished = true;
                await this.todoTaskService.UpdateAsync(task, token);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> MarkAsNotFinished(int id, CancellationToken token)
        {
            var task = await this.todoTaskService.GetAsync(id, token);

            if (task != null)
            {
                task.IsFinished = false;
                await this.todoTaskService.UpdateAsync(task, token);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

EisenhowerMatrix.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core Razor Pages</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?linkid=852130">Working with Razor Pages.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure App Service</a></li>
        </ul>
    </div>
</div>

EisenhowerMatrix.Web/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EisenhowerMatrix.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">EisenhowerMatrix.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/About">About</a></li>
                    <li><a asp-page="/Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - EisenhowerMatrix.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

EisenhowerMatrix.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>

<cite>
    "I have two kinds of problems, the urgent and the important.
    The urgent are not important, and the important are never urgent.""
    <p>President Dwight D. Eisenhower</p>
</cite>

EisenhowerMatrix.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home page";
}

<h2>@ViewData["Title"]</h2>

<nav>
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a asp-action="Index" asp-controller="TodoTaskOldSchool">Todo task old school</a></li>
        </ul>
    </div>
</nav>

EisenhowerMatrix.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EisenhowerMatrix.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-action="Index" asp-controller="Home" class="navbar-brand">EisenhowerMatrix.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-action="Index" asp-controller="Home">Home</a></li>
                    <li><a asp-action="About" asp-controller="Home">About</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - EisenhowerMatrix.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

EisenhowerMatrix.Web/Views/TodoTaskOldSchool/Create.cshtml
@model CreateTaskModel

@{
    ViewData["Title"] = "Create todo task old school page";
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-lg-6">
        <div class="panel">
            <div class="panel-body">
                <form asp-action="Create" method="post">
                    <div class="form-group">
                        <label for="Name">TODO:</label>
                        <input name="Name" type="text" placeholder="Learn C#" class="form-control" />
                        <span asp-validation-for="Name" class="danger"></span>
                    </div>
                    <div class="form-group">
                        <label for="Urgency">Urgency (from 0 to 10):</label>
                        <input name="Urgency" type="number" placeholder="" class="form-control" />
                        <span asp-validation-for="Urgency" class="danger"></span>
                    </div>
                    <div class="form-group">
                        <label for="Importance">Importance (from 0 to 10):</label>
                        <input name="Importance" type="number" placeholder="" class="form-control" />
                        <span asp-validation-for="Importance" class="danger"></span>
                    </div>
                    <input type="submit" value="Create" class="btn btn-success" />
                </form>
            </div>
        </div>
    </div>
</div>

EisenhowerMatrix.Web/Views/TodoTaskOldSchool/Index.cshtml
@model IndexModel

@{
    ViewData["Title"] = "Todo task old school page";
}

<h2>@ViewData["Title"]</h2>

<p>
    Here you can see old (before Ajax) era of working with data.
</p>

<div class="row">
    <div class="col-lg-6">
        <div class="row">
            <div class="col-lg-12">
                <a asp-action="Create" class="btn btn-success">Create new task</a>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <h3>TODO Tasks</h3>
                <table class="table table-condensed">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Urgency</th>
                            <th>Importance</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Tasks.Count == 0)
                        {
                            <tr>
                                <td colspan="5">
                                    No tasks
                                </td>
                            </tr>
                        }
                        else
                        {
                            foreach (var item in Model.Tasks)
                            {
                                <tr class="@(item.IsFinished ? "finished-task" : "")">
                                    <td>
                                        @item.Id
                                    </td>
                                    <td>
                                        @item.Name
                                    </td>
                                    <td>
                                        @item.Urgency
                                    </td>
                                    <td>
                                        @item.Importance
                                    </td>
                                    <td>
                                        <div class="row text-right">
                                            @if (item.IsFinished)
                                            {
                                                <form asp-action="MarkAsNotFinished" method="post" class="form-inline" style="display:inline">
                                                    <input name="id" type="hidden" value="@item.Id" />
                                                    <input type="submit" value="Unfinish" class="btn btn-primary btn-sm" />
                                                </form>
                                            }
                                            else
                                            {
                                                <form asp-action="MarkAsFinished" method="post" class="form-inline" style="display:inline">
                                                    <input name="id" type="hidden" value="@item.Id" />
                                                    <input type="submit" value="Finish" class="btn btn-warning btn-sm" />
                                                </form>
                                            }
                                            <form asp-action="Delete" method="post" class="form-inline" style="display:inline">
                                                <input name="id" type="hidden" value="@item.Id" />
                                                <input type="submit" value="Del" class="btn btn-danger btn-sm" />
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        Graph here
    </div>
</div>